### ISSUE TITLE
Pony 1.11 doesn't work with mail 2.7

### ISSUE THREAD

**Issue by benhocker** [benprew/pony#21]
It looks like you're working on Pony 1.12 so I wanted to make sure this got included with the release.

https://translate.google.com/translate?hl=en&sl=ja&u=https://qiita.com/tanakeiQ/items/5a2c48c5339b2ca90445&prev=search

**Comment by benprew** [comment]
Thanks Ben, I'll make sure that gets included.

**Comment by benprew** [comment]
Ok, Pony should work with mail 2.7 now.  And version 1.12 has been pushed live to rubygems.  Let me know if you run into problems.
