### ISSUE TITLE
versions and changelog

### ISSUE THREAD

**Issue by noraj** [benprew/pony#24]
There is gem release for 1.12, 1.13, 1.13.1:

![image](https://user-images.githubusercontent.com/16578570/57941233-b2362600-78ce-11e9-9c58-9a53b34bf4f1.png)

There is no github release for 1.12, 1.13 and 1.13.1:

![image](https://user-images.githubusercontent.com/16578570/57941204-9cc0fc00-78ce-11e9-9749-e24ad29f6331.png)

There is no tags for 1.12, 1.13 and 1.13.1:

![image](https://user-images.githubusercontent.com/16578570/57941186-8b77ef80-78ce-11e9-8453-e3de6e44621b.png)

There is no changelog.

**Comment by benprew** [comment]
I added tags for 1.12, 1.13 and 1.13.1.

1.31.1 fixes a warning message, so I didn't feel the need to include it in the changelog.  Here's the change if you're interested: https://github.com/benprew/pony/commit/b01c2a09eb99025aee79899aa5a3a2143e871248

Thanks
