### ISSUE TITLE
Special characters on email :to field causes Net::SMTPFatalError

### ISSUE THREAD

**Issue by FabioRos** [benprew/pony#25]
I get the error <`Net::SMTPFatalError (553 5.1.3 invalid local part)`> when the recipient of the email is an address that contains special chars. E.g. `emàìl@domain.com`. 
How can I solve this problem using this gem?

**Comment by benprew** [comment]
Fabio,

Special characters aren't allowed in email addresses.  Are you able to send
email to these addresses using other tools?

https://stackoverflow.com/questions/2049502/what-characters-are-allowed-in-an-email-address

**Comment by FabioRos** [comment]
Hi Ben,

Thank you for the fast response.

I've got a user with the email `****ò****@libero.it` and I sent an email with Gmail using an alias that contains the same character.

I saw the [RFC6532](https://tools.ietf.org/html/rfc6532) Standard and seems that it will support also Latin characters.

[https://stackoverflow.com/questions/760150/can-an-email-address-contain-international-non-english-characters](https://stackoverflow.com/questions/760150/can-an-email-address-contain-international-non-english-characters)

**Comment by benprew** [comment]
Fabio,

Good find, looks like I was wrong.

Also, the error you're getting is from the receiving mail server, so
it's probably a character encoding issue.  Are you converting the
string with the special character to Latin1?  Or is it a UTF-8 encoded
string?

Also, what version of ruby are you using?

Thanks

**Comment by FabioRos** [comment]
Hi Ben,

I'm using utf8 encoding without any force. The service is running with Sinatra gem(2.0.5) on ruby-2.5.3.

Could the problem be that the mail server itself doesn't support special characters?

Thank you, 
Fabio

**Comment by benprew** [comment]
Fabio,

According to my reading, that looks like it should work.  Try encoding the
to: email address into latin1 before passing it to pony, just to see if
that changes anything.

ex:

"emàìl@domain.com".encode('iso-8859-1')
